"""Add created_by column to User

Revision ID: 58168a60b622
Revises: f3709f43083e
Create Date: 2024-09-03 13:34:16.213632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58168a60b622'
down_revision = 'f3709f43083e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_user_created_by', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_created_by', type_='foreignkey')
        batch_op.drop_column('created_by')
    # ### end Alembic commands ###
